### ISSUE TITLE
Zeichen für DLRG

### ISSUE THREAD

**Issue by phjardas** [phjardas/taktische-zeichen#36]
Siehe https://www.dlrg.de/fileadmin/user_upload/DLRG.de/Fuer-Mitglieder/Einsatz/Gefahrenabwehr/DV102_TaktischeZeichen_DLRG110826.pdf ab Seite 54

**Comment by einsatzverwaltung** [comment]
Dort sind keine zusätzlichen Symbole o.ä. enthalten. Die Fachaufgabe Wasserrettung ist bereits in der Empfehlung der SKK enthalten. Die dort abgebildeten Symbole lassen sich alle mit dem Generator erzeugen, sobald die Fachaufgabe Wasserrettung eingebaut wurde.
Die Frage ist ob du die Unterstützung mehrere Symbole als Fachaufgabe einbauen willst. (Hubschrauber + Wasserrettung = "Hubschraubergestützte Wasserrettung"

**Comment by phjardas** [comment]
Ach nööö, so komplexes Zeug wollen wir erstmal nicht machen. 🙈

**Comment by einsatzverwaltung** [comment]
:-D
