### ISSUE TITLE
Feld unten links

### ISSUE THREAD

**Issue by white-gecko** [phjardas/taktische-zeichen#56]
Beim THW gibt es für Taktische Formationen auch unten links Angaben, wie z.B. Typ A oder Typ B (vgl. https://thwiki.org/t=Fachgruppe_Ortung).

Ich würde mich freuen, wenn ich das auch angeben kann.

![](https://upload.wikimedia.org/wikipedia/commons/1/15/Thw_stan_fgr_o_a.gif)

![](https://upload.wikimedia.org/wikipedia/commons/9/9e/Thw_stan_fgr_o_b.gif)

**Comment by phjardas** [comment]
@white-gecko Bitte schau dir mal [die Preview](https://deploy-preview-58--taktische-zeichen.netlify.app/demo/) an, erfüllt das deine Anforderungen?

**Comment by white-gecko** [comment]
Vielen Dank. Bei Versorgungs und Logistik Einheiten, bzw. Instandhaltung ist der Typ in dem Balken und nicht wie der Name der Organisation (zumindest im Fall der Instandhaltung) mit hoch gestellt.

![grafik](https://github.com/user-attachments/assets/dfdd6839-863e-46a4-9d41-3dd462028ab4)
![grafik](https://github.com/user-attachments/assets/d4d3674b-a416-4b63-ba9d-45d150659709)

**Comment by white-gecko** [comment]
Danke
