### ISSUE TITLE
Download *.svg file

### ISSUE THREAD

**Issue by johannes217** [phjardas/taktische-zeichen#60]
Hallo zusammen, 

wäre es möglich einen "Download as SVG" button an die Demo zu bauen. Ich würde mir gerne Zeichen herunterladen. Geht ja aktuell via Quellcode, wäre aber anderweitig deutlich einfacher.

Danke für das großartige Tool

**Comment by phjardas** [comment]
Nichts leichter als das. 😊

**Comment by phjardas** [comment]
✅ ist live.
